resources:
- name: 2m
  type: time
  source: 
    interval: 2m
jobs:
- name: cfusage 
  max_in_flight: 1
  plan:
  - get: cfusagerepo
  - task: cf-usage-task 
    file: cfusagerepo/tasks/usage-task.yml
    params:
      API_URL: {{API_URL}}
      USERNAME: {{USERNAME}}
      PASSWORD: {{PASSWORD}}
      ORG: {{ORG}}
      ENV: {{ENV}}
      TO: {{TO}}
      THRESHOLD: {{THRESHOLD}}
      AWS_ACCESS_KEY_ID: ((access-key-id))
      AWS_SECRET_ACCESS_KEY: ((secret-access-key))
      region_name: us-east-1
resources:
  - name: cfusagerepo
    type: git
    source: 
      uri: https://github.com/rajeshgundawar/Usage.git
      branch: master

