jobs:
- name: cfusage 
  max_in_flight: 1
  plan:
#  - get: 10m
#    trigger: true
  - get: cfusagerepo
  - task: cf-usage-task 
    file: cfusagerepo/tasks/usage-task.yml
    params:
      API_URL: {{API_URL}}
      USERNAME: {{USERNAME}}
      PASSWORD: {{PASSWORD}}
      ORG: {{ORG}}
      ENV: {{ENV}}
      TO: {{TO}}
      THRESHOLD: {{THRESHOLD}}
      AWS_ACCESS_KEY_ID: ((access-key-id))
      AWS_SECRET_ACCESS_KEY: ((secret-access-key))
      region_name: us-east-1
resources:
  - name: cfusagerepo
    type: git
    source: 
      uri: https://github.com/rajeshgundawar/Usage.git
      branch: master
      tag: latest
  - name: slack-alert
    type: slack-notification
    source:
      uri: https://hooks.slack.com/services/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
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
on_failure:
      put: slack-alert
      params:
        channel: '#sonic-internal'
        icon_emoji: ':concourse:'
        text: |
          :sample: Test
on_success:
      put: slack-alert
      params:
        channel: '#sonic-internal'
        icon_emoji: ':concourse:'
        text: |
          :sample: Test


#  - name: 10m
#    type: time
#    source:
#      interval: 10m
