---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: briandfrost/concourse-ubuntu
    tag: latest
inputs:
  - name: cfusagerepo
outputs:
  - name: email
run:
  path: cfusagerepo/scripts/usage-script.sh
